# Generated by Django 4.1.4 on 2022-12-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('text', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='blog_images')),
            ],
        ),
    ]
